version: "3.9"

services:
  db:
    image: postgres:16
    container_name: go-todo-postgres
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
      POSTGRES_DB: todo
    ports:
    - "5432:5432"